src/Entity/Image.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ImageRepository")
 */
class Image
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $product_id;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $bnoo;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProductId(): ?int
    {
        return $this->product_id;
    }

    public function setProductId(?int $product_id): self
    {
        $this->product_id = $product_id;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getBnoo(): ?string
    {
        return $this->bnoo;
    }

    public function setBnoo(?string $bnoo): self
    {
        $this->bnoo = $bnoo;

        return $this;
    }
}

src/Form/ImageType.php
<?php

namespace App\Form;

use App\Entity\Image;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ImageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('product_id')
            ->add('image')
            ->add('bnoo')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Image::class,
            'csrf_protection' => false,
        ]);
    }
}

src/Controller/ImageController.php
<?php

namespace App\Controller;

use App\Entity\Image;
use App\Form\ImageType;
use App\Repository\ImageRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/image")
 */
class ImageController extends AbstractController
{
    /**
     * @Route("/", name="image_index", methods="GET")
     */
    public function index(ImageRepository $imageRepository): Response
    {
        return $this->render('image/index.html.twig', ['images' => $imageRepository->findAll()]);
    }

    /**
     * @Route("/new/{pid}", name="image_new", methods="GET|POST")
     */
    public function new(Request $request, $pid, ImageRepository $imageRepository): Response
    {

        $imagelist = $imageRepository -> findBy(
            ['product_id' => $pid]
        );

        $image = new Image();
        $form = $this->createForm(ImageType::class, $image);
        $form->handleRequest($request);

        if ($request -> files -> get('imagename')) {
            $file = $request -> files -> get('imagename');
            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
            try {
                $file->move(
                    $this->getParameter('images_directory'),
                    $fileName
                );
            } catch (FileException $e) {
                // ... handle exception if something happens during file upload
            }
            $image -> setImage($fileName);
            $image -> setProductId($pid);

            $em = $this->getDoctrine()->getManager();
            $em->persist($image);
            $em->flush();

            return $this->redirectToRoute('image_new',array('pid' => $pid));
        }

        return $this->render('image/new.html.twig', [
            'image' => $image,
            'imagelist' => $imagelist,
            'pid' => $pid,
            'form' => $form->createView(),
        ]);
    }




    /**
     * @Route("/{id}", name="image_show", methods="GET")
     */
    public function show(Image $image): Response
    {
        return $this->render('image/show.html.twig', ['image' => $image]);
    }

    /**
     * @Route("/{id}/edit", name="image_edit", methods="GET|POST")
     */
    public function edit(Request $request, Image $image): Response
    {
        $form = $this->createForm(ImageType::class, $image);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('image_edit', ['id' => $image->getId()]);
        }

        return $this->render('image/edit.html.twig', [
            'image' => $image,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/{pid}", name="image_delete", methods="GET")
     */
    public function delete(Request $request, Image $image , $pid): Response
    {

            $em = $this->getDoctrine()->getManager();
            $em->remove($image);
            $em->flush();


        return $this->redirectToRoute('image_new',array('pid' => $pid));
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }




}

templates/image/_delete_form.html.twig
<form method="post" action="{{ path('image_delete', {'id': image.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ image.id) }}">
    <button class="btn">Delete</button>
</form>

templates/image/_form.html.twig
<form action="{{ path('image_new',{'pid': pid}) }}" method="post" enctype="multipart/form-data">
    Select image to upload:
    <input name="productid" type="hidden" value="{{ pid }}" type="number" >
    <input type="file"  name="imagename" id="fileToUpload">
    <input type="submit" value="Upload Image" name="submit">
</form>

templates/image/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Image{% endblock %}

{% block body %}
    <h1>Edit Image</h1>

    {{ include('image/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('image_index') }}">back to list</a>

    {{ include('image/_delete_form.html.twig') }}
{% endblock %}

templates/image/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Image index{% endblock %}

{% block body %}


    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Product_id</th>
                <th>Image</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for image in images %}
            <tr>
                <td>{{ image.id }}</td>
                <td>{{ image.productId }}</td>
                <td>{{ image.image }}</td>
                <td>
                    <a href="{{ path('image_show', {'id': image.id}) }}">show</a>
                    <a href="{{ path('image_edit', {'id': image.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('image_new') }}">Create new</a>
{% endblock %}

templates/image/new.html.twig
{% extends 'adminbase.html.twig' %}

{% block title %}New Image{% endblock %}

{% block body %}

    <div align="center">

    {{ include('image/_form.html.twig') }}

    <a href="{{ path('image_index') }}">back to list</a> <br>



    {% for image in imagelist %}
     <img src="{{ asset('uploads')}}/images/{{ image.image }}" height="100" >

        <a href="{{ path('image_delete', {'pid' : image.productid, 'id' : image.id }) }}" onclick="return confirm('Silnecek emin misin?');"  class="btn btn-danger btn-xs"> Sil</a>







    {% endfor %}




</div>

{% endblock %}

templates/image/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Image{% endblock %}

{% block body %}
    <h1>Image</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ image.id }}</td>
            </tr>
            <tr>
                <th>Product_id</th>
                <td>{{ image.productId }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ image.image }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('image_index') }}">back to list</a>

    <a href="{{ path('image_edit', {'id': image.id}) }}">edit</a>

    {{ include('image/_delete_form.html.twig') }}
{% endblock %}