src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $keywords;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $type;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $publisher_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $year;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $amount;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $price;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $sellprice;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $min;

    /**
     * @ORM\Column(type="text")
     */
    private $detail;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $writer_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $category_id;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $status;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getKeywords(): ?string
    {
        return $this->keywords;
    }

    public function setKeywords(?string $keywords): self
    {
        $this->keywords = $keywords;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(?int $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getPublisherId(): ?int
    {
        return $this->publisher_id;
    }

    public function setPublisherId(?int $publisher_id): self
    {
        $this->publisher_id = $publisher_id;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(?int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getAmount(): ?int
    {
        return $this->amount;
    }

    public function setAmount(?int $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getSellprice(): ?float
    {
        return $this->sellprice;
    }

    public function setSellprice(?float $sellprice): self
    {
        $this->sellprice = $sellprice;

        return $this;
    }

    public function getMin(): ?int
    {
        return $this->min;
    }

    public function setMin(?int $min): self
    {
        $this->min = $min;

        return $this;
    }

    public function getDetail(): ?string
    {
        return $this->detail;
    }

    public function setDetail(string $detail): self
    {
        $this->detail = $detail;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getWriterId(): ?int
    {
        return $this->writer_id;
    }

    public function setWriterId(?int $writer_id): self
    {
        $this->writer_id = $writer_id;

        return $this;
    }

    public function getCategoryId(): ?int
    {
        return $this->category_id;
    }

    public function setCategoryId(?int $category_id): self
    {
        $this->category_id = $category_id;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('keywords')
            ->add('description')
            ->add('type')
            ->add('publisher_id')
            ->add('year')
            ->add('amount')
            ->add('price')
            ->add('sellprice')
            ->add('min')
            ->add('detail')
            ->add('image')
            ->add('writer_id')
            ->add('category_id')
            ->add('status')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
            'csrf_protection' => false,
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Form\ProductType;
use App\Repository\CategoryRepository;
use App\Repository\ProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("admin/product")
 */
class ProductController extends AbstractController
{
    /**
     * @Route("/", name="product_index", methods="GET")
     */
    public function index(ProductRepository $productRepository): Response
    {
        return $this->render('product/index.html.twig', ['products' => $productRepository->findAll()]);
    }

    /**
     * @Route("/new", name="product_new", methods="GET|POST")
     */
    public function new(Request $request , CategoryRepository $categoryRepository): Response
    {
        $catlist = $categoryRepository -> findAll();
        $catname = $categoryRepository -> findBy( ['id' => 0]);
        $product = new Product();
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($product);
            $em->flush();

            return $this->redirectToRoute('product_index');
        }

        return $this->render('product/new.html.twig', [
            'product' => $product,
            'catlist' => $catlist,
            'catname' => $catname,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="product_show", methods="GET")
     */
    public function show(Product $product): Response
    {
        return $this->render('product/show.html.twig', ['product' => $product]);
    }

    /**
     * @Route("/{id}/edit", name="product_edit", methods="GET|POST")
     */
    public function edit(Request $request, Product $product, CategoryRepository $categoryRepository): Response
    {

        $catlist = $categoryRepository -> findAll();
        $catname = $categoryRepository -> findBy( ['id' => $product->getCategoryId()]);
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this -> addFlash('success','Kayit Güncelleme Başarılı');
            return $this->redirectToRoute('product_edit', ['id' => $product->getId()]);
        }

        return $this->render('product/edit.html.twig', [
            'product' => $product,
            'catlist' => $catlist,
            'catname' => $catname,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/{id}/iedit", name="product_iedit", methods="GET|POST")
     */
    public function iedit(Request $request,$id,Product $product): Response
    {
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('product_edit', ['id' => $product->getId()]);
        }

        return $this->render('product/i_edit.html.twig', [
            'product' => $product,
            'id' => $id,
            'form' => $form->createView(),
        ]);
    }




    /**
     * @Route("/{id}/iupdate", name="product_iupdate", methods="POST")
     */
    public function iupdate(Request $request, $id ,Product $product): Response
    {
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);
        $file = $request->files->get('imagename');
        $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
        try {
            $file->move(
                $this->getParameter('images_directory'),
                $fileName
            );
        } catch (FileException $e) {
            // ... handle exception if something happens during file upload
        }
        $product -> setImage($fileName);
        $this->getDoctrine()->getManager()->flush();

        return $this->redirectToRoute('product_iedit', ['id' => $product->getId()]);



    }

    /**
     * @Route("/{id}", name="product_delete", methods="DELETE")
     */
    public function delete(Request $request, Product $product): Response
    {
        if ($this->isCsrfTokenValid('delete'.$product->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($product);
            $em->flush();
        }

        return $this->redirectToRoute('product_index');
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }




}


templates/product/_delete_form.html.twig
<form method="post" action="{{ path('product_delete', {'id': product.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
    <button class="btn">Delete</button>
</form>

templates/product/_form.html.twig




<form action="#" class="form-actions" id="block-validate" novalidate="novalidate" method="post">


    <div class="form-group">
        <label class="control-label col-lg-4">Kategori</label>
        <div class="col-lg-10">
            <div class="sportformError parentFormpopup-validation formError"  >
                <select name="product[category_id]" class="validate[required] form-control" >
                    {%  if  (catname) %}
                        <option value="{{ product.categoryid}}">{{ catname[0].title }}</option>
                    {% endif %}
                    {%  for cat in catlist %}

                        <option value="{{ cat.id }}">{{ cat.title }} </option>
                    {% endfor %}
                </select>
            </div>
        </div>
    </div>



    <div class="form-group">
        <label class="control-label col-lg-4">Title</label>

        <div class="col-lg-4">
            <input type="text" id="email2" value="{{ product.title }}" name="product[title]" class="form-control">
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-lg-4">Keywords</label>
        <div class="col-lg-4">
            <input type="text" id="email2" value="{{ product.keywords }}" name="product[keywords]" class="form-control">
        </div>
    </div>


    <div class="form-group">
        <label class="control-label col-lg-4">Description</label>

        <div class="col-lg-4">
            <input type="text" id="password2" value="{{ product.description }}" name="product[description]" class="form-control">
        </div>
    </div>



    <div class="form-group">
        <label class="control-label col-lg-4">Aktif Durumu</label>
        <div class="col-lg-4">
            <div class="sportformError parentFormpopup-validation formError"  >
                <select name="product[status]"  id="sport" class="validate[required] form-control"  >
                    <option>{{ product.status }}</option>
                    <option selected >True</option>
                    <option> False</option>

                </select>
            </div>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-lg-4">Detail</label>
        <div class="col-lg-4">

            <textarea id="editor" name="product[detail]" rows="20" cols="30" > {{ product.detail }} </textarea>
        </div> </div>

    <br>

    <div class="form-actions no-margin-bottom" style="text-align:center;">
        <a href="{{ path('product_index') }}" class="btn btn-primary btn-grad" >Geri Dön</a>
        <input  type="submit" value="Kaydet" class="btn btn-primary btn-grad ">
    </div>
</form>


templates/product/edit.html.twig
{% extends 'adminbase.html.twig' %}

{% block body %}

    {{ include('messages.html.twig')}}

    {{ include('product/_form.html.twig', {'button_label': 'Update'}) }}

    <script>
        ClassicEditor
            .create( document.querySelector( '#editor' ) )
            .catch( error => {
                console.error( error );
            } );
    </script>



{% endblock %}

templates/product/i_edit.html.twig
{% extends 'adminbase.html.twig' %}

{% block title %}Edit Product Image{% endblock %}

{% block body %}
    <h4>{{ product.title }}</h4>

    <form action="{{ path('product_iupdate',{'id': id}) }}" method="post" enctype="multipart/form-data">




        Select image to upload:
        <input name="productid" value="{{ id }}" type="number" >
        <input type="file" name="imagename" id="fileToUpload">
        <input type="submit" value="Upload Image" name="submit">
    </form>


    {% if product.image != null %}

        <img src="{{ asset('uploads')  }}/images/{{ product.image }}"  >

    {% endif %}


{% endblock %}

templates/product/index.html.twig
{% extends 'adminbase.html.twig' %}




{% block body %}




<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-heading" align="center">
            Alt Kategoriler
        </div> <br>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Title</th>
                    <th>Keywords</th>
                    <th>Description</th>
                    <th>Type</th>
                    <th>Year</th>
                    <th>Detail</th>
                    <th>Image</th>
                    <th>Gallery</th>
                    <th>Category_id</th>
                    <th>Status</th>
                    <th>Güncelle</th>
                    <th>Sil</th>

                </tr>
                </thead>
                <tbody>
                {% for product in products %}
                    <tr>
                        <td>{{ product.id }}</td>
                        <td>{{ product.title }}</td>
                        <td>{{ product.keywords }}</td>
                        <td>{{ product.description }}</td>
                        <td>{{ product.type }}</td>
                        <td>{{ product.year }}</td>
                        <td>{{ product.detail }}</td>
                        <td>
                            <a href="javascript:openWin('{{ path('product_iedit',{'id':product.id})}}','','toolbar=no,location=no,directories=0,status=no,top=100,left=200,menuBar=no,scrollBars=no,resizable=no,width=600,height=500');">

                                {% if product.image == null %}
                                    Fotoğraf Ekle
                                {% else %}
                                    <img src="{{ asset('uploads')  }}/images/{{ product.image }}" height="40" width="80">

                                {% endif %}
                            </a>
                        </td>
                        <td>
                            <a href="javascript:openWin('{{ path('image_new',{'pid':product.id})}}','','toolbar=no,location=no,directories=0,status=no,top=100,left=200,menuBar=no,scrollBars=no,resizable=no,width=1000,height=800');">
                                <img src="{{ asset('images')}}/search.png" height="32">
                            </a>
                        </td>


                        <td>{{ product.categoryId }}</td>

                        <td>{{ product.status }}</td>
                        <td> <a href="{{ path('product_edit', {'id': product.id }) }}" class="btn btn-primary"><i class="icon-pencil icon-white"></i> Güncelle</a></td>
                        <td> <a href="{{ path('product_delete', {'id': product.id }) }}" class="btn btn-primary"><i class="icon-pencil icon-white"></i> Sil</a></td>

                    </tr>
                {% else %}
                    <tr>
                        <td colspan="18">Kayıt Bulunamadı</td>
                    </tr>
                {% endfor %}
                </tbody>


            </table>



            <a href="{{ path('product_new') }}" class="btn btn-primary">Ekle</a>

        </div>

    </div>

    </div>
</div>






{% endblock %}



templates/product/new.html.twig
{% extends 'adminbase.html.twig' %}

{% block title %}Ürün Ekle {% endblock %}

{% block body %}
    <div align="center">
    <h4>Ürün Ekle</h4>
</div>
    {{ include('product/_form.html.twig') }}


{% endblock %}

templates/product/show.html.twig
{% extends 'adminbase.html.twig' %}

{% block title %}Product{% endblock %}

{% block body %}
    <h1>Product</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ product.id }}</td>
        </tr>
        <tr>
            <th>Title</th>
            <td>{{ product.title }}</td>
        </tr>
        <tr>
            <th>Keywords</th>
            <td>{{ product.keywords }}</td>
        </tr>
        <tr>
            <th>Description</th>
            <td>{{ product.description }}</td>
        </tr>
        <tr>
            <th>Type</th>
            <td>{{ product.type }}</td>
        </tr>
        <tr>
            <th>Publisher_id</th>
            <td>{{ product.publisherId }}</td>
        </tr>
        <tr>
            <th>Year</th>
            <td>{{ product.year }}</td>
        </tr>
        <tr>
            <th>Amount</th>
            <td>{{ product.amount }}</td>
        </tr>
        <tr>
            <th>Price</th>
            <td>{{ product.price }}</td>
        </tr>
        <tr>
            <th>Sellprice</th>
            <td>{{ product.sellprice }}</td>
        </tr>
        <tr>
            <th>Min</th>
            <td>{{ product.min }}</td>
        </tr>
        <tr>
            <th>Detail</th>
            <td>{{ product.detail }}</td>
        </tr>
        <tr>
            <th>Image</th>
            <td>{{ product.image }}</td>
        </tr>
        <tr>
            <th>Writer_id</th>
            <td>{{ product.writerId }}</td>
        </tr>
        <tr>
            <th>Category_id</th>
            <td>{{ product.categoryId }}</td>
        </tr>
        <tr>
            <th>Status</th>
            <td>{{ product.status }}</td>
        </tr>
        </tbody>
    </table>

    <a href="{{ path('product_index') }}">back to list</a>

    <a href="{{ path('product_edit', {'id': product.id}) }}">edit</a>

    {{ include('product/_delete_form.html.twig') }}
{% endblock %}